version: "3.8"

services:
  backend:
    build:
      context: ./backend          # Bygger från backend-mappen
      dockerfile: Dockerfile
    ports:
      - "5000:5000"               # Exponerar port 5000 utåt
    env_file:
      - ./backend/.env            # (om du vill läsa in API-keys)
    environment:
      NODE_ENV: "production"      # valfritt, men bra om du vill kör prd-läge
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend         # Bygger från frontend-mappen
      dockerfile: Dockerfile
    ports:
      - "3000:3000"               # Exponerar port 3000 utåt
    depends_on:
      - backend
    environment:
      # Om du vill att frontend ska anropa backend lokalt:
      REACT_APP_API_BASE_URL: "http://localhost:5000"
      # Ovannämnda variabel (REACT_APP_API_BASE_URL) kan i din React-kod
      # anropas via process.env.REACT_APP_API_BASE_URL
    restart: unless-stopped
