version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    ports:
      - "5000:5000"
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - forum-scraper-network

networks:
  forum-scraper-network:
    driver: bridge