version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      # Exempel på miljövariabler (kasta in vad du behöver!)
      NODE_ENV: "production"
      PORT: "5000"
      OPENAI_API_KEY: "3YN7rHqsH3NiXosTl8iUpgdCTKNS37ciHKaLQifoLw3bQrd3CxZ4sc1h0qFe7fnfOHvE4T3BlbkFJdFpmksgPakjV68DTGfm_2uUF4KETN2YlP1ogGcygrUXbOVdIfsS77JZxohMS4eN3C"
      GEMINI_API_KEY: "AIzaSyCSgDMlx9DI10"
      FRONTEND_URL: "http://localhost:5000"
    restart: unless-stopped
