version: "3.8"

services:
  flashgpt:
    image: elfgren89/flashgpt
    container_name: flashgpt
    ports:
      - "3000:3000"
      - "5000:5000"
    env_file: 
      - ./backend/.env  # Load environment variables at runtime
    environment:
      - NODE_ENV=production
